parameters:
    taskAzureResourceManagerConnection: ""
    taskResourceGroupName: ""
    taskEnvironmentFilePath: ""
    taskLocation: ""
    taskSubscriptionId: ""
    taskOverideParameters: ""

steps:
    - template: arm-resources-steps-deploy.yml
      parameters:
          name: AzureResourceManagerTemplateDeployment@3
          displayName: "Deploy Resources to Azure"
          azureResourceManagerConnection: ${{ parameters.taskAzureResourceManagerConnection }}
          resourceGroupName: ${{ parameters.taskResourceGroupName }}
          file: "$(Pipeline.Workspace)/drop/Resources/ResourcesDeploy.json"
          csmParametersFile: ${{ parameters.taskEnvironmentFilePath }}
          Location: ${{ parameters.taskLocation }}
          subscriptionId: ${{ parameters.taskSubscriptionId }}
          overrideParameters: ${{ parameters.taskOverideParameters }}
    - task: AzureFunctionApp@1
      displayName: "Azure Function App Deploy"
      inputs:
          ConnectedServiceNameARM: ${{ parameters.taskAzureResourceManagerConnection }}
          azureSubscription: ${{ parameters.taskAzureResourceManagerConnection }}
          appType: functionApp
          appName: ${{ replace(parameters.taskResourceGroupName, 'rg', 'func')}}
          package: "$(Pipeline.Workspace)/drop/AzureEvent.Functions.zip"
          deploymentMethod: "auto"
          RuntimeStack: "dotnet"
          RuntimeVersion: "6.0"
          StartupCommand: "AzureEvent.Function.dll"
          ScriptType: "CSharp"
          ConfigurationSettings: "-FUNCTIONS_WORKER_RUNTIME dotnet"

    - template: arm-resources-steps-deploy.yml
      parameters:
          name: AzureResourceManagerTemplateDeployment@3
          displayName: "Deploy Event Grid Subscriptions to Azure"
          azureResourceManagerConnection: ${{ parameters.taskAzureResourceManagerConnection }}
          resourceGroupName: ${{ parameters.taskResourceGroupName }}
          file: "$(Pipeline.Workspace)/drop/Resources/ResourcesDeployEventGrid.json"
          csmParametersFile: ${{ parameters.taskEnvironmentFilePath }}
          Location: ${{ parameters.taskLocation }}
          subscriptionId: ${{ parameters.taskSubscriptionId }}
          overrideParameters: ${{ parameters.taskOverideParameters }}
